# Generated by Django 5.2.17 on 2026-09-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="request_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hash of the request payload; used to detect idempotency conflicts.",
                max_length=64,
            ),
        ),
    ]
